import React from "react";
import axios from 'axios'
import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import { GiThreeFriends } from 'react-icons/gi'
import Link from 'next/link'
import { Divider } from '@chakra-ui/react'
import { AiOutlineCopyrightCircle } from 'react-icons/ai'


export default function Home() {
  const router = useRouter()
  const API_URL = "http://localhost:1997"
  const [dataUser, setDataUser] = React.useState('')

  const keepLogin = () => {
    let socmedLog = localStorage.getItem('socmedLog');
    if (socmedLog) {
      axios.get(API_URL + `/users/keep?id=${socmedLog}`)
        .then((res) => {
          if (res.data.idusers) {
            setDataUser(res.data)
          }
        }).catch((err) => {
          console.log(err);
        })
    }
  }

  const redirect = () => {
    router.push({
      pathname: '/timeline'
    })
  }

  React.useEffect(() => {
    keepLogin()
  }, []);

  return <div>
    {dataUser ?
      redirect()
      :
      <div className={styles.container}>
        <Head>
          <title>MyFriend</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='container'>
          <div className={styles.main}>
            <div className='d-flex'>
              <GiThreeFriends size={50} /> <span className='fs-1 fw-bold'>MyFriend</span>
            </div>
            <div style={{ height: 200 }}>
            </div>
            <div className='row'>
              <div className='col-8 d-none d-md-block'>
                <span className='fw-bold fs-1 text-dark' style={{ fontFamily: 'monospace' }}>Find your friend here.</span>
                <p className='w-75 fw-bold fs-4 mt-3'>The most powerful tool for real-time tracking, organizing, and engagement your life. Reach your happiness here.</p>
              </div>
              <div className='col-md-4 col-12'>
                <div className='card rounded shadow align-items-center p-5' style={{ backgroundColor: 'aliceblue' }}>
                  <div className='text-center'>
                    <span className='fs-4 fw-bold'>Login with your MyFriend account</span>
                    <Divider className='my-3' />
                    <Link href='/login'>
                      <button className='btn btn-primary btn-lg w-100'>Log in</button>
                    </Link>
                    <Divider className='my-3' />
                    <div className='d-flex'>
                      <span className='fs-5 text-muted my-auto'>New to MyFriend?</span>
                      <Link href='/register'>
                        <span type='button' className='fs-5 nav-link'>Sign up now</span>
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <footer className={styles.footer}>
            <a className='fw-bold'>
              < AiOutlineCopyrightCircle /> 2022 MyFriend.Inc
            </a>
          </footer>
        </div>
      </div>
    }
  </div>
}
