import React from "react";
import Axios from 'axios'
import Head from 'next/head'
import { BiMailSend } from "react-icons/bi";

const ResendPage = (props) => {
    const API_URL = "http://localhost:1997"
    const handleResend = async () => {
        try {
            let token = localStorage.getItem('socmedLog');
            console.log(token)
            let res = await Axios.get(API_URL + `/users/resend`,
                {
                    headers: {
                        'Authorization': `Bearer ${token}`
                    }
                }
            )
            if (res.data.idusers) {
                localStorage.setItem('socmedLog', res.data.token);
            }
        } catch (error) {
            console.log(error)
        }
    }


    return <div>
        <Head>
            <title>Verification</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='container w-100 bg-white' style={{ marginTop: 100 }}>
            <BiMailSend size={200} className="m-auto" />
            <p className="text-muted text-center">You are not Verified, you must resend link for Verification</p>
            <br />
            <button type="button" className="btn btn-success w-25 position-relative" style={{ marginLeft: 500 }} onClick={() => handleResend()} >Resend Link Verification</button>
        </div>
    </div>
}

export default ResendPage